---
name: Getting started
on:
  push:
    branches:
      - feature1
  pull_request:
    branches:
      - feature1
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo What is in the directory
          ls -a
          echo
          echo 3. Is Git installed?
          git --version
