---
name: Getting started
on:
  push:
    branches:
      - feature1
  pull_request:
    branches:
      - feature1
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo What is in the directory
          ls -a
          echo
          echo 2. is Java installed?
          java -version
          echo 3. Is Git installed?
          git --version
          echo 4. What build tools are installed?
          mav --version
          echo
          echo 5. Where is the android SDK root?
          echo $ANDROID_SDK_ROOT
          echo
          echo 6. Where are Selenium jars?
          echo $SELENUM_JAR_PATH
          echo
          echo 7. What is the workspace location?
          echo $RUNNER_WORKSPACE
          echo
          echo 8. Who is running this script?
          whoami
          echo 9. How is this disc laid out?
          df
          wcho 10. What environment variables are available?
          env
